name: Format Check

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  format:
    name: Check gofmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'

      - name: Check formatting with gofmt
        run: |
          set -e
          diff -u <(echo "$(gofmt -l . | grep -v '^$' | sort)") <(echo "$(find . -name '*.go' -print0 | xargs -0 gofmt -l | grep -v '^$' | sort)")
          if [ $? -ne 0 ]; then
            echo "Code formatting issues found. Please run 'gofmt -w .' to fix."
            exit 1
          fi