name: Go Imports Check

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  imports:
    name: Check goimports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check imports with goimports
        run: |
          set -e
          if ! goimports -l . | grep -v '^$' ; then
            echo "Go import issues found. Please run 'goimports -w .' to fix."
            exit 1
          fi