name: Release Workflow

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.21.3'

            - name: Determine Version
              id: version
              run: echo "::set-output name=version::$(grep -oP '(?<=^## )\d+\.\d+\.\d+' CHANGELOG.md | head -1)"

            - name: Create Git Tag
              run: |
                  if [ "${{ steps.version.outputs.version != '' }}" == "true" ]; then
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git tag -a "v${{ steps.version.outputs.version }}" -m "Version v${{ steps.version.outputs.version }}"
                    git push origin "v${{ steps.version.outputs.version }}" --follow-tags
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install GoReleaser
              run: |
                  curl -sL https://github.com/goreleaser/goreleaser/releases/download/v1.2.3/goreleaser_Linux_x86_64.tar.gz | tar -xz
                  sudo mv goreleaser /usr/local/bin/

            - name: Build and Release
              run: goreleaser release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ENVIROMENT: production
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
              if: steps.version.outputs.version != ''
