name: Release Workflow

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.21.3'

            - name: Install Goreleaser
              run: |
                  curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s -- -b $(go env GOPATH)/bin
              if: success()

            - name: Determine Version
              id: version
              run: echo "::set-output name=version::$(grep -oP '(?<=^## )\d+\.\d+\.\d+' CHANGELOG.md | head -1)"

            - name: Create Git Tag
              run: |
                if [ "${{ steps.version.outputs.version != '' }}" == "true" ]; then
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git tag -a "vtest" -m "Version vtest"
                  git push origin "vtest" -u ${{ secrets.GH_TOKEN }}
                fi

            # - name: Build and Release
            #   run: goreleaser release --clean
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            #       ENVIROMENT: production
            #       GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            #       GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            #   if: steps.version.outputs.version != ''
